### ISSUE TITLE
Port to fuse v3

### ISSUE THREAD

**Issue by KOLANICH** [bobvanderlinden/mbrfs#3]
Very few fixes are needed for that.

**Comment by bobvanderlinden** [comment]
If you know what the fixes are feel free to create a PR.

**Comment by KOLANICH** [comment]
Just an additional argument in one function call + fuse3 in pkgconfig in the makefile. Unfortunately I have deleted the repo with my fixes accidentially (when deleted the dir with the image from which I have copied everything I needed). There were also some compilation warnings that definitely require fixing, since they can cause memory corruption (and are errors, if C++ compiler is used instead of C one), but for me everything worked perfectly even it had been compiled with the warnings.

**Comment by bobvanderlinden** [comment]
Solved by #4
